[[redirects]]
  from = "/customize"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
